### ISSUE TITLE
ValueError: The scenario_dir does not point to a directory.

### ISSUE THREAD

**Issue by serapergun** [lionyouko/veinsgym_lowerloss#1]
@lionyouko Thank you so much for this sharing.

I tried to run the project immediately.
I checked the versions of protobuf and zmq.

But I have latest version of protobuf 4.21.2
You wrote it should be 10.1.

Also I got an error on trivialRL as:
ValueError: The scenario_dir does not point to a directory.

I think it is because of this line : "os.path.dirname(os.path.abspath(__file__)), "..", "properlowerloss""

What should I do?

Regards,
Serap

**Comment by serapergun** [comment]
@lionyouko 
And also when I changed as:
"scenario_dir": "/home......Downloads/veinsgym_lowerloss-master/scenario/",

I got an error:
FileNotFoundError: [Errno 2] No such file or directory: './run'

**Comment by lionyouko** [comment]
> @lionyouko Thank you so much for this sharing.
> 
> I tried to run the project immediately. I checked the versions of protobuf and zmq.
> 
> But I have latest version of protobuf 4.21.2 You wrote it should be 10.1.
> 
> Also I got an error on trivialRL as: ValueError: The scenario_dir does not point to a directory.
> 
> I think it is because of this line : "os.path.dirname(os.path.abspath(**file**)), "..", "properlowerloss""
> 
> What should I do?
> 
> Regards, Serap

You may want to look at READ.md again, I wasn't aware the list point 10 wasn't showing as intended. 

The line is correct, it tries to find the entire path up to the point where the python script is running  (agent folder) and go back only one dir (root dir where properlowerloss-[x86_64/le] is) and then tries to find properlowerloss. Please try to print to which these commands are point until u get the right location of "properlowerloss-[x86_64/le]".

**Comment by lionyouko** [comment]
> @lionyouko And also when I changed as: "scenario_dir": "/home......Downloads/veinsgym_lowerloss-master/scenario/",
> 
> I got an error: FileNotFoundError: [Errno 2] No such file or directory: './run'

I see, you were trying to hardcode the path, right?
So in that case just take away /scenario/ part as we don't have "scenario" folder.

**Comment by serapergun** [comment]
@lionyouko 
Thank you, by using hadrcode the path is used, other method is not used I did not understand why.

But (again) I got this message:

`Args:  {'debug': False, 'tool': None, 'verbose': False, 'arguments': None}
Omnet Args:  ['-uCmdenv', '-cGeneral', '--seed-set=0', '--*.manager.seed=0', '--*.gym_connection.port=5555']
I go run now!
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required`


And then:

`TimeoutError:` Veins instance did not send a request within 30.0 seconds
DEBUG:root:Veins process 145430 was shut down already with returncode 1.`

**Comment by serapergun** [comment]
@lionyouko I want to ask something, too.
I could not get over this issue nearly one month.

In my project, I changed some parameters on omnetpp.ini file also applType of nodes.
But in the simulation part, there is no difference with the before.

Also I added one more configuration. There is no change.

After that I changed ini file's location, it still runs the same.

I change observation and action spaces in omnetpp.ini file. But could not see any affect.

What am I doing wrong?
Help, please

**Comment by lionyouko** [comment]
> @lionyouko Thank you, by using hadrcode the path is used, other method is not used I did not understand why.
> 
> But (again) I got this message:
> 
> `Args: {'debug': False, 'tool': None, 'verbose': False, 'arguments': None} Omnet Args: ['-uCmdenv', '-cGeneral', '--seed-set=0', '--*.manager.seed=0', '--*.gym_connection.port=5555'] I go run now! sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper sudo: a password is required`
> 
> And then:
> 
> `TimeoutError:` Veins instance did not send a request within 30.0 seconds DEBUG:root:Veins process 145430 was shut down already with returncode 1.`

please take a look at run script. You going to see codlin = ["sudo"] + (...).
Take ["sudo"] away.

**Comment by lionyouko** [comment]
> @lionyouko I want to ask something, too. I could not get over this issue nearly one month.
> 
> In my project, I changed some parameters on omnetpp.ini file also applType of nodes. But in the simulation part, there is no difference with the before.
> 
> Also I added one more configuration. There is no change.
> 
> After that I changed ini file's location, it still runs the same.
> 
> I change observation and action spaces in omnetpp.ini file. But could not see any affect.
> 
> What am I doing wrong? Help, please

I am not sure what it could be. When you load simulation, are you loading the right config of the scenario? You may notice that, for example, this properlowerloss has NoGymConnection, General, MultipleGyms, MultipleGymsOne configs. In Python (agent) file, you must choose the one you want to run. 

```
gym.register(
    id="veins-v1",
    entry_point="veins_gym:VeinsEnv",
    # stuff that goes here needs to be the same in the init of the env class
    kwargs={
        "scenario_dir": os.path.relpath(
            os.path.join(
                os.path.dirname(os.path.abspath(__file__)), "..", "properlowerloss"
            )
        ),

        "timeout": 50.0,
        "print_veins_stdout": True,
        "action_serializer": serialize_action,
        "run_veins": True,  # start veins through Veins-Gym
        "port": 5551,  # pick a port to use
        # to run in a GUI, use:
        "user_interface": "Cmdenv",
        # "timeout": -1,
        "config": "MultipleGymsOne"
    },
)

```

There is a config parameter.

**Comment by serapergun** [comment]
@lionyouko Thank you for returning.
Yes I am aware of this. I added different config files with different applTypes.
When I don't use "config" line, I think the General config is selected by default.
But when I want to use different config files I could not see any changes.

By the way, you have got progress on veins-gym.
Do you advice while studying is it logical to change serpentine or dcc environments to other projects? Or make a project from the beginning? I am really stuck :(
Regards

**Comment by serapergun** [comment]
@lionyouko 
I took away [sudo] like you said. And got this:
`INFO:root:Env created
INFO:root:Closing VeinsEnv.
DEBUG:root:Listening on configured port 5555
DEBUG:root:Launching veins experiment using command `['./run', '-uCmdenv', '-cGeneral', '--seed-set=0', '--*.manager.seed=0', '--*.gym_connection.port=5555']`
DEBUG:root:Veins process launched with pid 14847
INFO:root:Launched veins experiment, waiting for request.
Args:  {'debug': False, 'tool': None, 'verbose': False, 'arguments': None}
Omnet Args:  ['-uCmdenv', '-cGeneral', '--seed-set=0', '--*.manager.seed=0', '--*.gym_connection.port=5555']
I go run now!
Args:  {'debug': False, 'tool': None, 'verbose': False, 'arguments': None}
Omnet Args:  []
I go run now!
Args:  {'debug': False, 'tool': None, 'verbose': False, 'arguments': None}
Omnet Args:  []
I go run now!`

It continues till the timeout.

**Comment by serapergun** [comment]
@lionyouko 
Do you have any advice for this issue?
Thanks
